// Lisää footer kaikille sivuille
document.addEventListener('DOMContentLoaded', function() {
    const footer = document.createElement('footer');
    footer.className = 'footer';
    footer.innerHTML = `
        <div class="footer-links">
            <a href="./blog_01.html">Kannattaako auto päivittää uudempaan?</a>
            <span class="separator">|</span>
            <a href="./blog_02.html">Yksityisleasingin kannattavuus vs. auton omistaminen</a>
            <span class="separator">|</span>
            <a href="./rahoitusvertailu.html">Rahoitusvertailu (uusi vs. käytetty)</a>
            <!-- BRAND_LINKS_START -->
            <span class="separator">|</span>
            <a href="./alfa_romeo.html">Alfa Romeo</a>
            <span class="separator">|</span>
            <a href="./aston_martin.html">Aston Martin</a>
            <span class="separator">|</span>
            <a href="./audi.html">Audi</a>
            <span class="separator">|</span>
            <a href="./bentley.html">Bentley</a>
            <span class="separator">|</span>
            <a href="./bmw.html">BMW</a>
            <span class="separator">|</span>
            <a href="./buick.html">Buick</a>
            <span class="separator">|</span>
            <a href="./byd.html">BYD</a>
            <span class="separator">|</span>
            <a href="./cadillac.html">Cadillac</a>
            <span class="separator">|</span>
            <a href="./chevrolet.html">Chevrolet</a>
            <span class="separator">|</span>
            <a href="./chrysler.html">Chrysler</a>
            <span class="separator">|</span>
            <a href="./citroen.html">Citroen</a>
            <span class="separator">|</span>
            <a href="./cupra.html">Cupra</a>
            <span class="separator">|</span>
            <a href="./dacia.html">Dacia</a>
            <span class="separator">|</span>
            <a href="./dodge.html">Dodge</a>
            <span class="separator">|</span>
            <a href="./ferrari.html">Ferrari</a>
            <span class="separator">|</span>
            <a href="./fiat.html">Fiat</a>
            <span class="separator">|</span>
            <a href="./ford.html">Ford</a>
            <span class="separator">|</span>
            <a href="./genesis.html">Genesis</a>
            <span class="separator">|</span>
            <a href="./gmc.html">GMC</a>
            <span class="separator">|</span>
            <a href="./honda.html">Honda</a>
            <span class="separator">|</span>
            <a href="./hummer.html">Hummer</a>
            <span class="separator">|</span>
            <a href="./hyundai.html">Hyundai</a>
            <span class="separator">|</span>
            <a href="./infiniti.html">Infiniti</a>
            <span class="separator">|</span>
            <a href="./jaguar.html">Jaguar</a>
            <span class="separator">|</span>
            <a href="./jeep.html">Jeep</a>
            <span class="separator">|</span>
            <a href="./kia.html">Kia</a>
            <span class="separator">|</span>
            <a href="./lamborghini.html">Lamborghini</a>
            <span class="separator">|</span>
            <a href="./lancia.html">Lancia</a>
            <span class="separator">|</span>
            <a href="./land_rover.html">Land Rover</a>
            <span class="separator">|</span>
            <a href="./lexus.html">Lexus</a>
            <span class="separator">|</span>
            <a href="./lincoln.html">Lincoln</a>
            <span class="separator">|</span>
            <a href="./lotus.html">Lotus</a>
            <span class="separator">|</span>
            <a href="./maserati.html">Maserati</a>
            <span class="separator">|</span>
            <a href="./maybach.html">Maybach</a>
            <span class="separator">|</span>
            <a href="./mazda.html">Mazda</a>
            <span class="separator">|</span>
            <a href="./mclaren.html">McLaren</a>
            <span class="separator">|</span>
            <a href="./mercedes.html">Mercedes-Benz</a>
            <span class="separator">|</span>
            <a href="./mini.html">Mini</a>
            <span class="separator">|</span>
            <a href="./mitsubishi.html">Mitsubishi</a>
            <span class="separator">|</span>
            <a href="./nissan.html">Nissan</a>
            <span class="separator">|</span>
            <a href="./opel.html">Opel</a>
            <span class="separator">|</span>
            <a href="./peugeot.html">Peugeot</a>
            <span class="separator">|</span>
            <a href="./pontiac.html">Pontiac</a>
            <span class="separator">|</span>
            <a href="./porsche.html">Porsche</a>
            <span class="separator">|</span>
            <a href="./renault.html">Renault</a>
            <span class="separator">|</span>
            <a href="./rolls_royce.html">Rolls-Royce</a>
            <span class="separator">|</span>
            <a href="./saab.html">Saab</a>
            <span class="separator">|</span>
            <a href="./seat.html">Seat</a>
            <span class="separator">|</span>
            <a href="./skoda.html">Skoda</a>
            <span class="separator">|</span>
            <a href="./smart.html">Smart</a>
            <span class="separator">|</span>
            <a href="./srt.html">SRT</a>
            <span class="separator">|</span>
            <a href="./subaru.html">Subaru</a>
            <span class="separator">|</span>
            <a href="./suzuki.html">Suzuki</a>
            <span class="separator">|</span>
            <a href="./tesla.html">Tesla</a>
            <span class="separator">|</span>
            <a href="./toyota.html">Toyota</a>
            <span class="separator">|</span>
            <a href="./vw.html">Volkswagen</a>
            <span class="separator">|</span>
            <a href="./volvo.html">Volvo</a>
            <!-- BRAND_LINKS_END -->
            <span class="separator">|</span>
            <a href="./terms_explanations.html">Termit</a>
            <span class="separator">|</span>
            <a href="./terms.html">Käyttöehdot</a>
            <span class="separator">|</span>
            <a href="mailto:admin@autollehinta.fi">Ota yhteyttä</a>
        </div>
    `;
    document.body.appendChild(footer);

    var insight = document.createElement('script');
    insight.src = '/market_brand_insight.js';
    insight.defer = true;
    document.body.appendChild(insight);
}); 